### ISSUE TITLE
meta tag syntax

### ISSUE THREAD

**Issue by ArchitectFromMars** [terrifricker/recall-group#3]
**The \<head\> tag of index.html shows:**
```html
<meta content="width: device-width...
// notice how a colon follows 'width'
```
-vs-

```html
<meta content="width=device-width...
// equals sign follows 'width'
```

I wasn't sure if the syntax was incorrect, since it looks strange to use equals sign inside an attribute, but these resources seem to suggest otherwise. Not sure whether it has an impact or it can be left as is. Just wanted to point it out. We'll see how it works in production 😀

**RESOURCES FOR REFERENCE:**
https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag#viewport_basics

https://www.w3schools.com/tags/tag_meta.asp

**Comment by terrifricker** [comment]
You are exactly right!  Thanks for finding that and for the kindness in pointing it out.  Giving the resources for reference was a great idea, too.

Do you want to do the pull request for this item?
