### ISSUE TITLE
Add semantic html to <body>

### ISSUE THREAD

**Issue by terrifricker** [terrifricker/recall-group#7]
For an easy start, add skeleton html to index.html.  (Easy html, practice for git commands.)

Ask questions in this thread if needed.

**Comment by ArchitectFromMars** [comment]
Awesome! Just finishing up ver 1.0 of the boilerplate **index.html**. Will start git push shortly, then do PR. Exciting!

**Comment by ArchitectFromMars** [comment]
PR sent a minute ago. I will mark the comment as Closed. Happy reviewing!
